import { Inter } from "next/font/google";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import { getLocale } from "next-intl/server";
import Navbar from './../components/navbar/Navbar';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();

  
  return (
    <html lang={locale}>
         <body className={inter.className}>
     <NextIntlClientProvider messages={messages}>

        <Navbar/>
         
         {children}
         
     </NextIntlClientProvider>
         </body>
    </html>
  );
}
